#!/bin/env ruby
# encoding: utf-8

module CitiesList
  DatabaseCleaner.clean_with(:truncation, :only => ['cities'])
  City.create(:id=>1,:name=>"Alavieska",:region_id=>919)
  City.create(:id=>2,:name=>"Hyrynsalmi",:region_id=>919)
  City.create(:id=>3,:name=>"Kuusamo",:region_id=>919)
  City.create(:id=>4,:name=>"Lumijoki",:region_id=>919)
  City.create(:id=>5,:name=>"Muhos",:region_id=>919)
  City.create(:id=>6,:name=>"Nivala",:region_id=>919)
  City.create(:id=>7,:name=>"Oulunsalo",:region_id=>919)
  City.create(:id=>8,:name=>"Inari",:region_id=>920)
  City.create(:id=>9,:name=>"Kolari",:region_id=>920)
  City.create(:id=>10,:name=>"Muonio",:region_id=>920)
  City.create(:id=>11,:name=>"Posio",:region_id=>920)
  City.create(:id=>12,:name=>"Rovaniemi",:region_id=>920)
  City.create(:id=>13,:name=>"Salla",:region_id=>920)
  City.create(:id=>14,:name=>"Tornio",:region_id=>920)
  City.create(:id=>15,:name=>"Utsjoki",:region_id=>920)
  City.create(:id=>16,:name=>"Askola",:region_id=>921)
  City.create(:id=>17,:name=>"Helsinki",:region_id=>921)
  City.create(:id=>18,:name=>"Jokioinen",:region_id=>921)
  City.create(:id=>19,:name=>"Kouvola",:region_id=>921)
  City.create(:id=>20,:name=>"Lahti",:region_id=>921)
  City.create(:id=>21,:name=>"Nastola",:region_id=>921)
  City.create(:id=>22,:name=>"Orimattila",:region_id=>921)
  City.create(:id=>23,:name=>"Enonkoski",:region_id=>922)
  City.create(:id=>24,:name=>"Hirvensalmi",:region_id=>922)
  City.create(:id=>25,:name=>"Ilomantsi",:region_id=>922)
  City.create(:id=>26,:name=>"Juva",:region_id=>922)
  City.create(:id=>27,:name=>"Kuopio",:region_id=>922)
  City.create(:id=>28,:name=>"Liperi",:region_id=>922)
  City.create(:id=>29,:name=>"Mikkeli",:region_id=>922)
  City.create(:id=>30,:name=>"Nurmes",:region_id=>922)
  City.create(:id=>31,:name=>"Akaa",:region_id=>923)
  City.create(:id=>32,:name=>"Jakobstad",:region_id=>923)
  City.create(:id=>33,:name=>"Pori",:region_id=>923)
  City.create(:id=>34,:name=>"Salo",:region_id=>923)
  City.create(:id=>35,:name=>"Sastamala",:region_id=>923)
  City.create(:id=>36,:name=>"Turku",:region_id=>923)
  City.create(:id=>37,:name=>"Ulvila",:region_id=>923)
  City.create(:id=>38,:name=>"Ylöjärvi",:region_id=>923)
end