require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ForkedIdeasController do

  # This should return the minimal set of attributes required to create a valid
  # ForkedIdea. As you add validations to ForkedIdea, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "translated_ideas_at" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ForkedIdeasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all forked_ideas as @forked_ideas" do
      forked_idea = ForkedIdea.create! valid_attributes
      get :index, {}, valid_session
      assigns(:forked_ideas).should eq([forked_idea])
    end
  end

  describe "GET show" do
    it "assigns the requested forked_idea as @forked_idea" do
      forked_idea = ForkedIdea.create! valid_attributes
      get :show, {:id => forked_idea.to_param}, valid_session
      assigns(:forked_idea).should eq(forked_idea)
    end
  end

  describe "GET new" do
    it "assigns a new forked_idea as @forked_idea" do
      get :new, {}, valid_session
      assigns(:forked_idea).should be_a_new(ForkedIdea)
    end
  end

  describe "GET edit" do
    it "assigns the requested forked_idea as @forked_idea" do
      forked_idea = ForkedIdea.create! valid_attributes
      get :edit, {:id => forked_idea.to_param}, valid_session
      assigns(:forked_idea).should eq(forked_idea)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ForkedIdea" do
        expect {
          post :create, {:forked_idea => valid_attributes}, valid_session
        }.to change(ForkedIdea, :count).by(1)
      end

      it "assigns a newly created forked_idea as @forked_idea" do
        post :create, {:forked_idea => valid_attributes}, valid_session
        assigns(:forked_idea).should be_a(ForkedIdea)
        assigns(:forked_idea).should be_persisted
      end

      it "redirects to the created forked_idea" do
        post :create, {:forked_idea => valid_attributes}, valid_session
        response.should redirect_to(ForkedIdea.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved forked_idea as @forked_idea" do
        # Trigger the behavior that occurs when invalid params are submitted
        ForkedIdea.any_instance.stub(:save).and_return(false)
        post :create, {:forked_idea => { "translated_ideas_at" => "invalid value" }}, valid_session
        assigns(:forked_idea).should be_a_new(ForkedIdea)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ForkedIdea.any_instance.stub(:save).and_return(false)
        post :create, {:forked_idea => { "translated_ideas_at" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested forked_idea" do
        forked_idea = ForkedIdea.create! valid_attributes
        # Assuming there are no other forked_ideas in the database, this
        # specifies that the ForkedIdea created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ForkedIdea.any_instance.should_receive(:update_attributes).with({ "translated_ideas_at" => "1" })
        put :update, {:id => forked_idea.to_param, :forked_idea => { "translated_ideas_at" => "1" }}, valid_session
      end

      it "assigns the requested forked_idea as @forked_idea" do
        forked_idea = ForkedIdea.create! valid_attributes
        put :update, {:id => forked_idea.to_param, :forked_idea => valid_attributes}, valid_session
        assigns(:forked_idea).should eq(forked_idea)
      end

      it "redirects to the forked_idea" do
        forked_idea = ForkedIdea.create! valid_attributes
        put :update, {:id => forked_idea.to_param, :forked_idea => valid_attributes}, valid_session
        response.should redirect_to(forked_idea)
      end
    end

    describe "with invalid params" do
      it "assigns the forked_idea as @forked_idea" do
        forked_idea = ForkedIdea.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ForkedIdea.any_instance.stub(:save).and_return(false)
        put :update, {:id => forked_idea.to_param, :forked_idea => { "translated_ideas_at" => "invalid value" }}, valid_session
        assigns(:forked_idea).should eq(forked_idea)
      end

      it "re-renders the 'edit' template" do
        forked_idea = ForkedIdea.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ForkedIdea.any_instance.stub(:save).and_return(false)
        put :update, {:id => forked_idea.to_param, :forked_idea => { "translated_ideas_at" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested forked_idea" do
      forked_idea = ForkedIdea.create! valid_attributes
      expect {
        delete :destroy, {:id => forked_idea.to_param}, valid_session
      }.to change(ForkedIdea, :count).by(-1)
    end

    it "redirects to the forked_ideas list" do
      forked_idea = ForkedIdea.create! valid_attributes
      delete :destroy, {:id => forked_idea.to_param}, valid_session
      response.should redirect_to(forked_ideas_url)
    end
  end

end
